apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  backend:
    serviceName: guestbook-ui
    servicePort: 80
  rules:
  - host: guestbook.aks.local
    http:
      paths:
      - backend:
          serviceName: guestbook-ui
          servicePort: 80
  
