apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  rules:
    http:
      paths:
      path: - /guestbook-ui
      - backend:
          serviceName: guestbook-ui-1
          servicePort: 80
  
